name: CI Pipeline
on:
  pull_request:
      types:
        - opened
        - synchronize
  push:
  workflow_dispatch:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash -el {0}

    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.10"
        
        - name: Setup Miniconda
          uses: conda-incubator/setup-miniconda@v3
          with:
            auto-activate-base: false

        - name: Install dev environment
          run: conda env create -f envs/dev-environment.yml

        - name: Install test environment
          run: conda env create -f envs/test-environment.yml
        
        - name: Lint with flake8
          run: conda run -n gameshelf-dev flake8 .
        
        - name: Run tests with pytest
          run: conda run -n gameshelf-test pytest